export const PRODUCT_LIST_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_LIST = 'PRODUCT_LIST'
export const PRODUCT_LIST_FAIL = 'PRODUCT_CREATE_FAIL'
// export const PRODUCT_LIST_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'

export const CREATE_PRODUCT='CREATE_PRODUCT'
export const EDIT_PRODUCT='EDIT_PRODUCT'
export const REMOVE_PRODUCT='REMOVE_PRODUCT'

export const FOOTBALL_LIST="FOOTBALL_LIST"


