import { images } from "../Assets/Images";

export const header = [
  { id: "name", label: "Name", minWidth: 150 },
  {
    id: "email",
    label: "Email",
    minWidth: 170,
  },
  {
    id: "accounttype",
    label: "Account Type",
    minWidth: 120,
  },
  {
    id: "sports",
    label: "Sports",
    minWidth: 100,
  },
  {
    id: "skill1",
    label: "Skill 1",
    minWidth: 100,
  },
  {
    id: "skill2",
    label: "Skill 2",
    minWidth: 100,
  },
  {
    id: "skill3",
    label: "Skill 3",
    minWidth: 80,
  },
  {
    id: "action",
    label: "Action",
    minWidth: 85,
    align: "center",
  },
];

export const trophyHeader = [
  { id: "name", label: "Name", minWidth: 80 },
  {
    id: "email",
    label: "Email",
    minWidth: 80,
  },
  {
    id: "accounttype",
    label: "Account Type",
    minWidth: 80,
  },
  {
    id: "action",
    label: "Action",
    minWidth: 20,
    align: "center",
  },
];

export const userData = [
  {
    id: 1,
    name: "Ish",
    email: "ish@gmail.com",
    accounttype: "Athlete",
    sport: "Football",
    skill1: "Ball Control",
    skill2: "Dribble",
    skill3: "LeaderShip",
    authimg1: images.idCardFront,
    authimg2: images.idCardFront,
  },
  {
    id: 2,
    name: "Ahmad",
    email: "ahmd@gmail.com",
    accounttype: "Athlete",
    sport: "BaseBall",
    skill1: "Agility",
    skill2: "Hitting",
    skill3: "Pitching",
    authimg1: images.idCardFront,
    authimg2: images.idCardFront,
  },
  {
    id: 3,
    name: "Ali",
    email: "ali@gmail.com",
    accounttype: "Athlete",
    sport: "Cricket",
    skill1: "Right Arm Fast",
    skill2: "Running",
    skill3: "Catching",
    authimg1: images.idCardFront,
    authimg2: images.idCardFront,
  },
  {
    id: 4,
    name: "Fahad",
    email: "fahad@gmail.com",
    accounttype: "Coach",
    sport: "Bxing",
    skill1: "Accuracy",
    skill2: "Chin",
    skill3: "Cross",
  },
  {
    id: 5,
    name: "Talha",
    email: "talha@gmail.com",
    accounttype: "Athlete",
    sport: "Cricket",
    skill1: "Right Arm Fast",
    skill2: "Running",
    skill3: "Spin Bowl",
  },
  {
    id: 6,
    name: "Umair",
    email: "umair@gmail.com",
    accounttype: "Athlete",
    sport: "Cricket",
    skill1: "Right Arm Fast",
    skill2: "Cordination",
    skill3: "Running",
    authimg1: images.idCardFront,
    authimg2: images.idCardFront,
  },
  {
    id: 7,
    name: "Ahmad",
    email: "ahmd@gmail.com",
    accounttype: "Manager",
    sport: "BaseBall",
    skill1: "",
    skill2: "",
    skill3: "",
  },
  {
    id: 8,
    name: "pakistan",
    email: "Zaid@gmail.com",
    accounttype: "Athlete",
    sport: "Cricket",
    skill1: "Right Arm Fast",
    skill2: "Running",
    skill3: "Catching",
  },
  {
    id: 9,
    name: "pakistan",
    email: "Zaid@gmail.com",
    accounttype: "Athlete",
    sport: "Cricket",
    skill1: "Right Arm Fast",
    skill2: "Running",
    skill3: "Catching",
  },
  {
    id: 10,
    name: "pakistan",
    email: "Zaid@gmail.com",
    accounttype: "Athlete",
    sport: "Cricket",
    skill1: "Right Arm Fast",
    skill2: "Running",
    skill3: "Catching",
    authimg1: images.idCardFront,
    authimg2: images.idCardFront,
  },
  {
    id: 11,
    name: "pakistan",
    email: "Zaid@gmail.com",
    accounttype: "Athlete",
    sport: "Cricket",
    skill1: "Right Arm Fast",
    skill2: "Running",
    skill3: "Catching",
  },
];
